name: test
on:
  push:
  pull_request:

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - MacOs
        py:
          - "3.10"
    steps:
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v3
        # - name: Install soundlibs MacOs
        #   run: brew install libsndfile
      - name: Install dependencies
        run: python3.10 -m pip install coremltools onnxruntime numpy
      - name: Run a coreml inference
        run: python3.10 predict.py
